<a href="https://colab.research.google.com/github/KavyaPremaseelan/Machine-Learning-Codes-Implemented-using-Packages/blob/main/Ada_Boost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#load data
train=pd.read_csv('https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/train.csv')
test=pd.read_csv('https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Titanic/test.csv')

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [5]:
train.set_index("PassengerId",inplace=True)
test.set_index("PassengerId",inplace=True)

In [6]:
train

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
test

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [8]:
y_train=train["Survived"]

In [9]:
train.drop(labels="Survived",axis=1,inplace=True)

In [10]:
train.shape

(891, 10)

In [11]:
train_test = train.append(test) #since the dataset is not large enough we are appending

<ipython-input-11-a93f9a324811>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_test = train.append(test) #since the dataset is not large enough we are appending

In [12]:
train_test

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [13]:
columns_to_drop=["Name","Age","SibSp","Ticket","Cabin","Parch","Embarked"]
train_test.drop(labels=columns_to_drop,axis=1,inplace=True)

In [14]:
train_test

             Pclass     Sex      Fare
PassengerId
1                 3    male    7.2500
2                 1  female   71.2833
3                 3  female    7.9250
4                 1  female   53.1000
5                 3    male    8.0500
...             ...     ...       ...
1305              3    male    8.0500
1306              1  female  108.9000
1307              3    male    7.2500
1308              3    male    8.0500
1309              3    male   22.3583

[1309 rows x 3 columns]

In [15]:
train_test_dummies = pd.get_dummies(train_test,columns=["Sex"])

In [16]:
train_test_dummies.shape

(1309, 4)

In [17]:
train_test_dummies.isnull().sum()

Pclass        0
Fare          1
Sex_female    0
Sex_male      0
dtype: int64

In [18]:
train_test_dummies.fillna(value=0.0,inplace=True)

In [19]:
X_train = train_test_dummies.values[0:891]
X_test = train_test_dummies.values[891:]

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_scale=scaler.fit_transform(X_train)
X_test_scale=scaler.transform(X_test)

In [21]:
from sklearn.model_selection import train_test_split
X_train_sub,X_validation_sub,y_train_sub,y_validation_sub=train_test_split(X_train_scale,y_train,random_state=0) #validation is test here

In [22]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [39]:
n_estimators = 100
ada = AdaBoostClassifier(n_estimators=n_estimators, random_state=0)
ada.fit(X_train_sub, y_train_sub)
print("Accuracy score (training): {0:.3f}".format(ada.score(X_train_sub, y_train_sub)))
print("Accuracy score (validation): {0:.3f}".format(ada.score(X_validation_sub, y_validation_sub)))

Accuracy score (training): 0.814
Accuracy score (validation): 0.785

In [40]:
from sklearn.tree import DecisionTreeClassifier
n_estimators = 100
max_depth = 2
max_features = 2
# Create AdaBoost classifier
ada = AdaBoostClassifier(
    n_estimators=n_estimators,
    base_estimator=DecisionTreeClassifier(max_depth=max_depth, max_features=max_features),
    random_state=42
)
# Fit the model
ada.fit(X_train_sub, y_train_sub)
# Evaluate on training and validation sets
print("Accuracy score (training): {0:.3f}".format(ada.score(X_train_sub, y_train_sub)))
print("Accuracy score (validation): {0:.3f}".format(ada.score(X_validation_sub, y_validation_sub)))

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(

Accuracy score (training): 0.882
Accuracy score (validation): 0.798